[table]
entity = "objekt"
row_click = "navigate"
row_click_route = "/objekte/:id"

[[table.columns]]
field = "bezeichnung"
label = "labels.objekt.bezeichnung"
sortable = true
width = "25%"

[[table.columns]]
field = "adresse"
label = "labels.objekt.adresse"
sortable = true
width = "30%"
template = "{adresse}, {plz} {ort}"

[[table.columns]]
field = "typ"
label = "labels.objekt.typ"
sortable = true
width = "10%"
display = "badge"
badge_colors = { wohnraum = "blue", gewerbe = "orange", gemischt = "purple" }

[[table.columns]]
field = "computed.anzahl_einheiten"
label = "labels.objekt.einheiten"
sortable = true
width = "10%"
align = "center"

[[table.columns]]
field = "computed.leerstand"
label = "labels.objekt.leerstand"
sortable = true
width = "10%"
align = "center"
highlight_if = { condition = "> 0", color = "yellow" }

[[table.columns]]
field = "computed.gesamt_flaeche"
label = "labels.objekt.flaeche"
sortable = true
width = "15%"
format = "number"
suffix = " mÂ²"

[table.row_actions]
edit = { icon = "Pencil", dialog = "forms/objekt.form" }
delete = { icon = "Trash2", confirm = true, confirm_message = "labels.confirm.objekt_loeschen" }
