[table]
entity = "zahlung"

[[table.columns]]
field = "datum"
label = "labels.zahlung.datum"
sortable = true
width = "12%"
format = "date"

[[table.columns]]
field = "vertrag.mieter.computed.display_name"
label = "labels.zahlung.mieter"
sortable = true
width = "20%"

[[table.columns]]
field = "vertrag.einheit.bezeichnung"
label = "labels.zahlung.einheit"
width = "15%"

[[table.columns]]
field = "betrag"
label = "labels.zahlung.betrag"
sortable = true
width = "12%"
format = "currency"

[[table.columns]]
field = "typ"
label = "labels.zahlung.typ"
sortable = true
width = "12%"
display = "badge"

[[table.columns]]
field = "monat_fuer"
label = "labels.zahlung.monat_fuer"
sortable = true
width = "10%"
format = "month"

[[table.columns]]
field = "verwendungszweck"
label = "labels.zahlung.verwendungszweck"
width = "19%"
truncate = 30

[table.row_actions]
edit = { icon = "Pencil", dialog = "forms/zahlung.form" }
delete = { icon = "Trash2", confirm = true }
