[table]
entity = "zaehler"

[[table.columns]]
field = "objekt.bezeichnung"
label = "labels.zaehler.objekt"
sortable = true
width = "20%"

[[table.columns]]
field = "einheit.bezeichnung"
label = "labels.zaehler.einheit"
width = "15%"
empty_text = "Hauptz√§hler"

[[table.columns]]
field = "typ"
label = "labels.zaehler.typ"
sortable = true
width = "12%"
display = "badge"

[[table.columns]]
field = "zaehlernummer"
label = "labels.zaehler.nummer"
width = "15%"

[[table.columns]]
field = "ist_hauptzaehler"
label = "labels.zaehler.haupt"
width = "8%"
display = "boolean_icon"

[[table.columns]]
field = "computed.letzter_stand.stand"
label = "labels.zaehler.letzter_stand"
width = "15%"
template = "{value} {messeinheit}"

[[table.columns]]
field = "computed.letzter_stand.datum"
label = "labels.zaehler.abgelesen_am"
sortable = true
width = "15%"
format = "date"

[table.row_actions]
ablesung = { icon = "Plus", dialog = "forms/zaehlerstand.form", defaults = { zaehler_id = ":id" } }
edit = { icon = "Pencil", dialog = "forms/zaehler.form" }
historie = { icon = "History", dialog = "dialogs/zaehler_historie" }
